```python
from climada.hazard import Centroids, TCTracks, TropCyclone
import geopandas as gpd
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
```


```python
# Load YASA (Fiji historical typhoon)
yasa_id = '2020346S13168'

# Load Track from IbTracks
yasa_track = TCTracks.from_ibtracs_netcdf(storm_id=yasa_id)

# Load Fiji custom centroids
filepath = 'fji_0.1_degree_grid_centroids_new.gpkg'
gdf = gpd.read_file(filepath)

# Climada Centroids
cent = Centroids.from_geodataframe(gdf) # include oceans
cent.set_dist_coast(precomputed=True) # THIS SOLVES THE ISSUE (comment this line to show the weird patterns in the intensity plots)

# TropCyclone class
tc = TropCyclone.from_tracks(
    yasa_track, centroids=cent, store_windfields=True, intensity_thres=0
)

# Let's look at Yasa (intensity plot)
name = 'Yasa'
ax = tc.plot_intensity(yasa_id)
ax.set_title(name, size=20)
plt.show()
```

    2024-01-18 10:08:26,403 - climada.hazard.tc_tracks - WARNING - The cached IBTrACS data set dates from 2023-06-07 23:07:38 (older than 180 days). Very likely, a more recent version is available. Consider manually removing the file /Users/federico/climada/data/IBTrACS.ALL.v04r00.nc and re-running this function, which will download the most recent version of the IBTrACS data set from the official URL.
    2024-01-18 10:08:29,847 - climada.hazard.centroids.centr - WARNING - Centroids.from_geodataframe has been deprecated and will be removed in a future version. Use ther default constructor instead.




![png](01.3_windfields_recreate_problem_files/01.3_windfields_recreate_problem_1_1.png)
